### PR TITLE
Allow configuration from `.vscode/settings.json` when in a Multi-root project.

### PR DESCRIPTION
**Pull request by WraithKenny**

### CODE REVIEW

**Comment by WraithKenny** [comment]
The conflict is only the version number

**Comment by WraithKenny** [comment]
Sorry for the white space in the diff, my code editor automatically does that.

**Comment by soderlind** [comment]
Thank you :)

**Comment by soderlind** [comment]
Found one error, if `${workspaceRoot}` is used, this will fail:
```php
        if (this.executablePath.startsWith("${workspaceRoot}") || this.executablePath.startsWith("${workspaceFolder}")) {
            this.addRootPath("${workspaceFolder}");
        }
```

**Comment by WraithKenny** [comment]
I don't think the code would've failed. `workspaceRoot` is deprecated (but still functional) and should generally be replaced with `workspaceFolder`. 

I see how it might be desirable to support it as it was previously, as workspaceRoot will resolve to the first folder (workspaceFolders[0]) instead of the current folder, if anyone wants to rely on that (its a bit hacky behavior). Maybe leave it as an undocumented feature :-)

**Pull request merged**
